export const tableContainerClass="table-auto border-collapse w-full  border border-slate-500"
export const tableHeaderClassFixed="text-center bg-slate-200 sticky top-0  border-y-2 border-slate-600 z-100"
export const tableHeaderClassNormal="text-center bg-slate-200   border-y-2 border-slate-600 z-100"
export const headerRowClass="text-12 font-semibold text-center uppercase border border-slate-600 "
export const tableDataClass="border text-center border-2 border-slate-700"